//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.Common.Reports.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportValues() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISSSTE.Tramites2016.Common.Reports.Resources.ReportValues", typeof(ReportValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string DefaultEmptyProcedureStatus {
            get {
                return ResourceManager.GetString("DefaultEmptyProcedureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de los tiempos.
        /// </summary>
        internal static string DefaultEndDate {
            get {
                return ResourceManager.GetString("DefaultEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen de los tiempos.
        /// </summary>
        internal static string DefaultStartDate {
            get {
                return ResourceManager.GetString("DefaultStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lodgment.
        /// </summary>
        internal static string LodgmentTypeFormat {
            get {
                return ResourceManager.GetString("LodgmentTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Footer.
        /// </summary>
        internal static string NameSubreportFooter {
            get {
                return ResourceManager.GetString("NameSubreportFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Header.
        /// </summary>
        internal static string NameSubreportHeader {
            get {
                return ResourceManager.GetString("NameSubreportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LodgmentData.
        /// </summary>
        internal static string NameSubreportLodgmentData {
            get {
                return ResourceManager.GetString("NameSubreportLodgmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LodgmentPerson.
        /// </summary>
        internal static string NameSubreportLodgmentPerson {
            get {
                return ResourceManager.GetString("NameSubreportLodgmentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PackageData.
        /// </summary>
        internal static string NameSubreportPackgeData {
            get {
                return ResourceManager.GetString("NameSubreportPackgeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PackagePerson.
        /// </summary>
        internal static string NameSubreportPackgePerson {
            get {
                return ResourceManager.GetString("NameSubreportPackgePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment.
        /// </summary>
        internal static string NameSubreportPayment {
            get {
                return ResourceManager.GetString("NameSubreportPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TransportationData.
        /// </summary>
        internal static string NameSubreportTransportationData {
            get {
                return ResourceManager.GetString("NameSubreportTransportationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TransportationItinerary.
        /// </summary>
        internal static string NameSubreportTransportationItinerary {
            get {
                return ResourceManager.GetString("NameSubreportTransportationItinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TransportationPerson.
        /// </summary>
        internal static string NameSubreportTransportationPerson {
            get {
                return ResourceManager.GetString("NameSubreportTransportationPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a package.
        /// </summary>
        internal static string PackgeTypeFormat {
            get {
                return ResourceManager.GetString("PackgeTypeFormat", resourceCulture);
            }
        }
    }
}
